AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SourceSequrityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>  
    Description: The specified security groups will be added to each mount target. You can specify one or more
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>  
    Description: Specify from 1 to 3 subnets in one vpc and different availability zones. Mount target will be created for each subnet

Conditions:
  # Very ugly solution by orashken https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/735
  Subnet1Exist:  
    Fn::Not: 
      - Fn::Equals:
        - Fn::Select:
          - 0
          - Fn::Split:
            - ","
            - Fn::Sub:
              # Use 3 comma delimiter for 3 subnets
              - ${SubnetsIds},,, 
              - { SubnetsIds: !Join [',', !Ref Subnets] }
        - ""
  Subnet2Exist:  
    Fn::Not: 
      - Fn::Equals:
        - Fn::Select:
          - 1
          - Fn::Split:
            - ","
            - Fn::Sub:
              - ${SubnetsIds},,, 
              - { SubnetsIds: !Join [',', !Ref Subnets] }
        - ""
  Subnet3Exist:  
     Fn::Not: 
      - Fn::Equals:
        - Fn::Select:
          - 2
          - Fn::Split:
            - ","
            - Fn::Sub:
              - ${SubnetsIds},,, 
              - { SubnetsIds: !Join [',', !Ref Subnets] }
        - ""

Resources:

  MountTarget:
    Type: 'AWS::EFS::MountTarget'
    Condition: Subnet1Exist
    Properties:
      FileSystemId: fs-0fcbce9bfac1d2791
      # here it is interesting, we add item to array
      SecurityGroups: !Split [",", !Join [ ",", [ !Join [ ",", !Ref SourceSequrityGroups], !Ref SecurityGroup ] ]]
        # - !Ref EfsSecurityGroup
      SubnetId: !Select [0, !Ref Subnets]      
  
  MountTarget2:
    Type: 'AWS::EFS::MountTarget'
    DependsOn: MountTarget
    Condition: Subnet2Exist
    Properties:
      FileSystemId: fs-0fcbce9bfac1d2791
      # here it is interesting. we add item to array
      SecurityGroups: !Split [",", !Join [ ",", [ !Join [ ",", !Ref SourceSequrityGroups], !Ref SecurityGroup ] ]]
        # - !Ref EfsSecurityGroup
      SubnetId: !Select [1, !Ref Subnets]     
  
  MountTarget3:
    Type: 'AWS::EFS::MountTarget'
    Condition: Subnet3Exist
    Properties:
      FileSystemId: fs-0fcbce9bfac1d2791
      # here it is interesting. we add item to array
      SecurityGroups: !Split [",", !Join [ ",", [ !Join [ ",", !Ref SourceSequrityGroups], !Ref SecurityGroup ] ]]
        # - !Ref EfsSecurityGroup
      SubnetId: !Select [2, !Ref Subnets]     

